### ISSUE TITLE
Default QI iterations setting too low

### ISSUE THREAD

**Issue by jwassenburg** [NynkeDekkerLab/BeadTracker#6]
As shown by testing, the default amount of QI iterations (3) is too low. Should be increased to 5.
[Tests for bead tracking by Qtrk.docx](https://github.com/NynkeDekkerLab/BeadTracker/files/55660/Tests.for.bead.tracking.by.Qtrk.docx)

**Comment by daimonie** [comment]
Interpretation: Change the default setting.

**Comment by daimonie** [comment]
Is defined as 5 in the type definition. 

BeadtrackerMain.vi second frame looks for a default config, likely to be beadtracker/bt2-config.xml which might overwrite these if no errors are found. However, if it is missing (such as it is for me) then there should be no problem. 

However, if I display the VI it seems that it starts at 1 rather than 3 or 5. I'm not sure why this is as I have no configuration file present and the default type is at five. There should be no updated settings for me, bnut changing the number and saving still doesn't give me the proper number. I'm not sure why it is changed; it is set to auto from type or something similar and this is five.

**Comment by daimonie** [comment]
I suggest just including a default file in the maintracker git. I'll speak to Richard for his default settings.

**Comment by mwdocter** [comment]
Hoi Josko,

Iets erg triviaals, maar heeft iemand bij de control rechts geklikt en  ‘set as default value’ gedaan? Dan zit de default waarde ergens in de vi verborgen.

Groeten, Margreet

**Comment by daimonie** [comment]
Added default-config.xml readout and a readout VI.

**Comment by daimonie** [comment]
NB: Also added UpdateCameraSettings.vi, which does the 'update camera settings part'.
